# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://renanxcortes.github.io
title: Renan Xavier Cortes
email: renanxcortes@gmail.com
author: Renan Xavier Cortes
description: "Renan's Personal Page"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
# Build sitemap
gems:
  - jekyll-sitemap

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - icon: github
    title: github
    url: https://github.com/renanxcortes
  - icon: envelope-o
    title: email
    url: mailto:renanxcortesl@gmail.com
  - icon: linkedin
    title: linkedin
    url: https://www.linkedin.com/in/renan-cortes-a3583a33/
  - icon: file-pdf-o
    title: CV
    url: img/RenanCortesCV.pdf
#  - icon: website
#    title: CV Lattes
#    url: http://lattes.cnpq.br/5399100590606067
#  - icon: twitter
#    title: twitter
#    url: https://twitter.com/danicassol

